# Generated by Django 4.2 on 2025-01-17 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='name',
        ),
        migrations.AddField(
            model_name='vendor',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='vendor',
            name='contact_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='vendor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='vendor',
            name='logo',
            field=models.ImageField(default='', upload_to='vendor_logos/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='vendor',
            name='store_name',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
