# Generated by Django 4.2.5 on 2025-01-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_alter_vendorproduct_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['position']},
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='created_at',
        ),
        migrations.AddField(
            model_name='productimage',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
