# Generated by Django 4.2 on 2025-01-18 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        # ('users', '0002_userprofile_user_type'),
        ('vendors', '0002_remove_vendor_name_vendor_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='address',
            new_name='shop_description',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='description',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='store_name',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='user',
        ),
        migrations.AddField(
            model_name='vendor',
            name='shop_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='user_profile',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to='users.userprofile'),
        ),
    ]
