# Generated by Django 4.2 on 2025-01-20 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_rename_address_vendor_shop_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='shop_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='shop_description',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='user_profile',
        ),
    ]
