# Generated by Django 4.2.5 on 2025-07-18 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0010_vendorproduct_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_order_delivered_at_order_dispute_raised_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_order_created', models.BooleanField(default=True)),
                ('email_order_paid', models.BooleanField(default=True)),
                ('email_order_shipped', models.BooleanField(default=False)),
                ('email_order_delivered', models.BooleanField(default=False)),
                ('email_payment_cleared', models.BooleanField(default=True)),
                ('email_dispute_raised', models.BooleanField(default=True)),
                ('email_low_stock', models.BooleanField(default=True)),
                ('email_reviews', models.BooleanField(default=True)),
                ('email_system_announcements', models.BooleanField(default=True)),
                ('app_order_created', models.BooleanField(default=True)),
                ('app_order_paid', models.BooleanField(default=True)),
                ('app_order_shipped', models.BooleanField(default=True)),
                ('app_order_delivered', models.BooleanField(default=True)),
                ('app_payment_cleared', models.BooleanField(default=True)),
                ('app_dispute_raised', models.BooleanField(default=True)),
                ('app_low_stock', models.BooleanField(default=True)),
                ('app_reviews', models.BooleanField(default=True)),
                ('app_system_announcements', models.BooleanField(default=True)),
                ('realtime_order_created', models.BooleanField(default=True)),
                ('realtime_order_paid', models.BooleanField(default=True)),
                ('realtime_order_shipped', models.BooleanField(default=False)),
                ('realtime_order_delivered', models.BooleanField(default=False)),
                ('realtime_payment_cleared', models.BooleanField(default=True)),
                ('realtime_dispute_raised', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('order_created', 'New Order'), ('order_paid', 'Order Paid'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('order_cancelled', 'Order Cancelled'), ('payment_cleared', 'Payment Cleared'), ('dispute_raised', 'Dispute Raised'), ('product_low_stock', 'Low Stock Alert'), ('product_out_of_stock', 'Out of Stock Alert'), ('review_received', 'New Review'), ('system_announcement', 'System Announcement')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['vendor', 'is_read'], name='notificatio_vendor__b23e39_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx')],
            },
        ),
    ]
