"""
Django settings for django_multivendor project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta  # Ensure timedelta is imported
import os
import importlib.util

# Helper function to check if a package is installed
def is_package_installed(package_name):
    return importlib.util.find_spec(package_name) is not None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

FRONTEND_URL = 'http://shop.bazro.ge'  # Update for Cloudflare tunnel

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!%mrkjmzu^xalr!*(_1#bo7z)8^gl=nzqip9d3)f)mq$-8e1ac'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'api.bazro.ge', 'shop.bazro.ge']

# Application definition

# Core Django apps
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'adminsortable2',  # Make sure this is included
]

# Project-specific apps
PROJECT_APPS = [
    'users',
    'vendors',  # This now handles all product functionality
    'cart',
    'orders',
    'payments',
    'payouts',
    'categories',
    'reviews',
    'shipping',
    'search',  # AI search functionality
    'ai_search',  # AI-powered search with Ollama
]

# Optional third-party apps, only added if installed
THIRD_PARTY_APPS = []

if is_package_installed('corsheaders'):
    THIRD_PARTY_APPS.append('corsheaders')

if is_package_installed('social_django'):
    THIRD_PARTY_APPS.append('social_django')

if is_package_installed('django_extensions'):
    THIRD_PARTY_APPS.append('django_extensions')

if is_package_installed('rest_framework_simplejwt.token_blacklist'):
    THIRD_PARTY_APPS.append('rest_framework_simplejwt.token_blacklist')

if is_package_installed('channels'):
    THIRD_PARTY_APPS.append('channels')

# Combine all apps
INSTALLED_APPS = INSTALLED_APPS + PROJECT_APPS + THIRD_PARTY_APPS

# Middleware configuration with conditional CORS
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
]

if is_package_installed('corsheaders'):
    MIDDLEWARE.append('corsheaders.middleware.CorsMiddleware')

MIDDLEWARE += [
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_multivendor.middleware.RequestResponseLoggingMiddleware',
]

# CORS settings if corsheaders is available
if is_package_installed('corsheaders'):
    CORS_ALLOW_ALL_ORIGINS = True
    CORS_ALLOW_HEADERS = [
        'accept',
        'accept-encoding',
        'authorization',
        'content-type',
        'dnt',
        'origin',
        'user-agent',
        'x-csrftoken',
        'x-requested-with',
        'x-master-token',  # Add this header to allow master token authentication
        'x-guest-session-key',  # Add this header to allow guest session key
        'x-vendor-id',  # Add this header to allow vendor ID in order management
    ]

    CORS_ALLOW_CREDENTIALS = True
    CORS_EXPOSE_HEADERS = ['Content-Type', 'X-CSRFToken']
    
    # Additional settings for proper preflight handling
    CORS_PREFLIGHT_MAX_AGE = 86400  # Cache preflight requests for 24 hours
    CORS_ALLOW_PRIVATE_NETWORK = True  # Allow local network access
    
    # Debug CORS issues
    import logging
    logging.getLogger('corsheaders').setLevel(logging.DEBUG)

    CORS_ALLOWED_ORIGINS = [
        'https://localhost:5173',
        'http://localhost:5173',
        'https://localhost:5174',
        'http://localhost:5174',
        'https://127.0.0.1:5173',
        'http://127.0.0.1:5173',
        'https://127.0.0.1:5174',
        'http://127.0.0.1:5174',
        'https://api.bazro.ge',
        'http://api.bazro.ge',
        'https://shop.bazro.ge',
        'http://shop.bazro.ge',
        'https://seller.bazro.ge',
        'http://seller.bazro.ge',
        'https://www.seller.bazro.ge',
        'http://www.seller.bazro.ge',
        'https://bazro.ge',
        'https://www.bazro.ge',
        'http://localhost:3000',
        'http://127.0.0.1:3000',
    ]

    CORS_ORIGIN_WHITELIST = CORS_ALLOWED_ORIGINS

    CORS_ALLOW_METHODS = [
        'DELETE',
        'GET',
        'OPTIONS',
        'PATCH',
        'POST',
        'PUT',
    ]

ROOT_URLCONF = 'django_multivendor.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Make sure this is updated
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_multivendor.wsgi.application'
ASGI_APPLICATION = 'django_multivendor.asgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'

# Define STATICFILES_DIRS to include the main static directory
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Define STATIC_ROOT for collectstatic
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'vendors.authentication.MasterTokenAuthentication',
    ],
    # Remove the default permission class to allow public access by default
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}

# Add Simple JWT settings
SIMPLE_JWT = {
    # Token lifetimes - industry standard for web applications
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),  # Shorter for security, longer than before
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),     # Longer refresh for better UX
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=15),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=7),
    
    # Token rotation for enhanced security
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': False,  # Temporarily disabled to test refresh issue
    'UPDATE_LAST_LOGIN': True,
    
    # Algorithm and signing
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': 'django_multivendor',
    
    # Authentication
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
    
    # Token classes
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',
    
    # Token refresh settings
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_REFRESH_LIFETIME_CLAIM': 'refresh_exp',
    
    # Blacklist settings
    'USE_BLACKLIST': is_package_installed('rest_framework_simplejwt.token_blacklist'),
    'BLACKLIST_AFTER_ROTATION': False,  # Temporarily disabled to test refresh issue
    
    # Custom claims
    'TOKEN_OBTAIN_SERIALIZER': 'rest_framework_simplejwt.serializers.TokenObtainPairSerializer',
    'TOKEN_REFRESH_SERIALIZER': 'rest_framework_simplejwt.serializers.TokenRefreshSerializer',
    'TOKEN_VERIFY_SERIALIZER': 'rest_framework_simplejwt.serializers.TokenVerifySerializer',
    'TOKEN_BLACKLIST_SERIALIZER': 'rest_framework_simplejwt.serializers.TokenBlacklistSerializer',
    
    # Error handling
    'LEEWAY': 10,  # 10 seconds leeway for clock skew
}

# Master token for frontend access
MASTER_ACCESS_TOKEN = 'your-super-secret-token'  # Must match exactly what you're sending

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': 'debug.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'vendors': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'rest_framework_simplejwt': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
}

# Authentication backends with conditional social auth
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

if is_package_installed('social_core.backends.google'):
    AUTHENTICATION_BACKENDS.insert(0, 'social_core.backends.google.GoogleOAuth2')

if is_package_installed('social_core.backends.facebook'):
    AUTHENTICATION_BACKENDS.insert(0, 'social_core.backends.facebook.FacebookOAuth2')

# Google OAuth2 settings
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '13306343475-jfr7948k9qrtsohfbpukkrmsgcvf6kiu.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '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'
SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = [
    'https://www.googleapis.com/auth/userinfo.email',
    'https://www.googleapis.com/auth/userinfo.profile',
]

# IMPORTANT: Update this line to use HTTPS since Google enforces HTTPS for OAuth redirect URIs
SOCIAL_AUTH_GOOGLE_OAUTH2_REDIRECT_URI = 'https://shop.bazro.ge/auth/callback'

# JWT token creation after successful social auth
SOCIAL_AUTH_PIPELINE = (
    'social_core.pipeline.social_auth.social_details',
    'social_core.pipeline.social_auth.social_uid',
    'social_core.pipeline.social_auth.auth_allowed',
    'social_core.pipeline.social_auth.social_user',
    'social_core.pipeline.user.get_username',
    'social_core.pipeline.user.create_user',
    'social_core.pipeline.social_auth.associate_user',
    'social_core.pipeline.social_auth.load_extra_data',
    'social_core.pipeline.user.user_details',
    'users.pipeline.create_jwt_token',  # Custom pipeline step
)

# Add this setting to force the redirect URI
SOCIAL_AUTH_GOOGLE_OAUTH2_AUTH_EXTRA_ARGUMENTS = {
    'redirect_uri': 'https://shop.bazro.ge/auth/callback'
}

# Override the default callback URL
SOCIAL_AUTH_URL_NAMESPACE = 'social'
SOCIAL_AUTH_LOGIN_REDIRECT_URL = 'https://shop.bazro.ge/auth/callback'
SOCIAL_AUTH_REDIRECT_IS_HTTPS = True

# Add Facebook OAuth Settings
SOCIAL_AUTH_FACEBOOK_KEY = '980299590637567'  # App ID
SOCIAL_AUTH_FACEBOOK_SECRET = 'b03af61c7593172da21275902236284c'  # App Secret
SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']
SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS = {
    'fields': 'id,name,email,first_name,last_name',
    'auth_type': 'reauthenticate'  # Force re-authentication
}
SOCIAL_AUTH_FACEBOOK_EXTRA_DATA = [
    ('name', 'name'),
    ('email', 'email'),
    ('first_name', 'first_name'),
    ('last_name', 'last_name'),
]
SOCIAL_AUTH_FACEBOOK_REDIRECT_URI = 'http://shop.bazro.ge/auth/callback'
SOCIAL_AUTH_FACEBOOK_AUTH_EXTRA_ARGUMENTS = {
    'redirect_uri': SOCIAL_AUTH_FACEBOOK_REDIRECT_URI
}
SOCIAL_AUTH_FACEBOOK_API_VERSION = '16.0'  # Use latest stable version
SOCIAL_AUTH_FACEBOOK_OAUTH2_SCOPE = ['email']
SOCIAL_AUTH_FACEBOOK_OAUTH2_METHOD = 'GET'  # Some setups work better with GET

# Enable debug logging for social auth
SOCIAL_AUTH_LOGGING_LEVEL = 'DEBUG'

# SSL Settings
SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Update for Cloudflare tunnels - no need for SSL certificates
# Comment out or remove SSL certificate configuration
# SSL_CERTIFICATE = BASE_DIR / 'certificates' / 'localhost.crt'
# SSL_PRIVATE_KEY = BASE_DIR / 'certificates' / 'localhost.key'

# Update OAuth settings to include Cloudflare domain
SOCIAL_AUTH_ALLOWED_REDIRECT_HOSTS = ['localhost:5173', '127.0.0.1:5173', 'shop.bazro.ge']

# Add Cloudflare domains to trusted origins
CSRF_TRUSTED_ORIGINS = [
    'https://localhost:8000',
    'http://localhost:8000',
    'https://127.0.0.1:8000',
    'http://127.0.0.1:8000',
    'https://api.bazro.ge',
    'http://api.bazro.ge',
    'https://shop.bazro.ge',
    'http://shop.bazro.ge',
]

# Update CORS settings for HTTPS
CORS_ALLOWED_ORIGINS = [
    'https://localhost:5173',
    'http://localhost:5173',
    'https://localhost:5174',
    'http://localhost:5174',
    'https://127.0.0.1:5173',
    'http://127.0.0.1:5173',
    'https://127.0.0.1:5174',
    'http://127.0.0.1:5174',
    'https://api.bazro.ge',
    'http://api.bazro.ge',
    'https://shop.bazro.ge',
    'http://shop.bazro.ge',
    'https://seller.bazro.ge',
    'http://seller.bazro.ge',
    'https://www.seller.bazro.ge',
    'http://www.seller.bazro.ge',
    'https://bazro.ge',
    'https://www.bazro.ge',
    'http://localhost:3000',
    'http://127.0.0.1:3000',
]

CORS_ORIGIN_WHITELIST = CORS_ALLOWED_ORIGINS

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-master-token',  # Add this header to allow master token authentication
    'x-guest-session-key',  # Add this header to allow guest session key
    'x-vendor-id',  # Add this header to allow vendor ID in order management
]

# AI Search Configuration
OLLAMA_API_URL = 'http://localhost:11434/api/generate'
OLLAMA_MODEL = 'gemma:7b'
AI_SEARCH_DEBUG = True  # Set to False in production
AI_SEARCH_CACHE_TIMEOUT = 3600  # 1 hour cache

# Channel Layers Configuration for WebSocket Support
if is_package_installed('channels'):
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [("127.0.0.1", 6379)],
            },
        },
    }
else:
    # In-memory channel layer for development (fallback)
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer"
        }
    }
