# Generated by Django 4.2.5 on 2025-07-22 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
    ]
