# Generated by Django 4.2.5 on 2025-02-02 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_alter_productimage_options_and_more'),
        ('payouts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('processed_orders', models.IntegerField(default=0)),
                ('total_amount_processed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_logs', to='vendors.vendor')),
            ],
            options={
                'get_latest_by': 'last_checked',
            },
        ),
    ]
