# Generated by Django 4.2.5 on 2025-03-22 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_add_attribute_models'),
        ('categories', 'add_display_order_category'),
    ]

    operations = [
    ]
