# Generated by Django 4.2.5 on 2025-03-22 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_add_display_order_category'),
        ('categories', '0003_merge_20250322_1410'),
    ]

    operations = [
    ]
