# Generated by Django 4.2.5 on 2025-06-03 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_merge_20250322_1708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'ordering': ['display_order', 'name']},
        ),
    ]
