# Generated by Django 4.2.5 on 2025-01-30 18:43

from django.db import migrations, models
import vendors.models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorproduct',
            name='video',
            field=models.FileField(blank=True, help_text='Upload product video file (MP4 recommended)', null=True, upload_to=vendors.models.product_video_path),
        ),
    ]
