# Generated by Django 4.2.5 on 2025-02-10 19:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import vendors.models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('vendors', '0003_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorproduct',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category'),
        ),
        migrations.AddField(
            model_name='vendorproduct',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='vendorproduct',
            name='is_hot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorproduct',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vendorproduct',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='vendorproduct',
            name='secondaryImage',
            field=models.ImageField(blank=True, null=True, upload_to=vendors.models.product_media_path),
        ),
    ]
