# Generated by Django 4.2.5

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_add_attribute_models'),
        ('vendors', '0004_vendorproduct_category_vendorproduct_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_value', models.TextField(blank=True, null=True)),
                ('number_value', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('boolean_value', models.BooleanField(blank=True, null=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_values', to='categories.attribute')),
                ('option_values', models.ManyToManyField(blank=True, related_name='product_values', to='categories.attributeoption')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='vendors.vendorproduct')),
            ],
            options={
                'unique_together': {('product', 'attribute')},
            },
        ),
    ]
