# Generated by Django 4.2.5 on 2025-03-22 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_add_attribute_values'),
        ('vendors', 'add_display_order'),
    ]

    operations = [
    ]
