# Generated by Django 4.2.5 on 2025-03-22 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_add_position_field'),
        ('vendors', '0006_merge_0005_add_attribute_values_add_display_order'),
    ]

    operations = [
    ]
