# Generated by Django 4.2.5 on 2025-03-23 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_vendorproduct_frequently_bought_together'),
        ('vendors', '0007_merge_20250322_1447'),
    ]

    operations = [
    ]
