# Generated by Django 4.2.5 on 2025-06-03 13:51

from django.db import migrations, models
import vendors.models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0008_merge_20250323_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorproduct',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendorproduct',
            name='secondaryImage',
            field=models.ImageField(blank=True, null=True, upload_to=vendors.models.product_thumbnail_path),
        ),
        migrations.AlterField(
            model_name='vendorproduct',
            name='thumbnail',
            field=models.ImageField(blank=True, default='vendor_products/default_thumbnail.png', upload_to=vendors.models.product_thumbnail_path),
        ),
    ]
