# Generated by Django 4.2.5 on 2025-06-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0009_add_brand_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorproduct',
            name='tags',
            field=models.TextField(blank=True, default='', help_text='Comma-separated tags for the product'),
        ),
    ]
