# Generated by Django 4.2.5 on 2025-03-03 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_userprofile_address'),
        ('users', '0005_wishlist'),
    ]

    operations = [
    ]
