# Generated by Django 4.2.5 on 2025-05-21 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_update_empty_emails'),
        ('users', '0006_merge_0005_remove_userprofile_address_0005_wishlist'),
    ]

    operations = [
    ]
