# Generated by Django 4.2 on 2025-01-17 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(default='', max_length=100, unique=True)),
                ('carrier', models.CharField(default='', max_length=50)),
                ('shipped_date', models.DateTimeField(blank=True, null=True)),
                ('estimated_delivery_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Shipped', 'Shipped'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered')], default='Shipped', max_length=20)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='orders.order')),
            ],
        ),
    ]
